Adds Swift Package Manager support and removes Cocoapods (Deprecated) * Fixes imports and tests * Updates Github workflow * Removes old server tests and fixes color tolerance for failing test * Updated C enums to NS_ENUM and pulls in changes from SimpleFeatures (sf-ios) and related dependencies to allow for Swift interoperability.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,14 +13,20 @@ jobs:
 
     steps:
     - name: Checkout Repository
-      uses: actions/checkout@v3
-    - name: Install Utilities
-      run: |
-        brew install automake
-        brew install libtool
-    - name: Install
-      run: |
-        pod repo update
-        pod install
+      uses: actions/checkout@v4
+
     - name: Build
-      run: xcodebuild build-for-testing -workspace geopackage-ios.xcworkspace -scheme geopackage-ios -destination 'platform=iOS Simulator,OS=latest,name=iPhone 14'
+      run: |
+        iphone_names=$(xcrun simctl list devices available --json | jq -r '.devices | to_entries[] | .value[] | select(.name | test("^iPhone [0-9]+")) | .name')
+        if [ -z "$iphone_names" ]; then echo "Error: No iPhone simulators found."; exit 1; fi
+        latest_iphone=$(echo "$iphone_names" | sort | tail -n 1)
+        echo "latest_iphone: $latest_iphone"
+        xcodebuild build -scheme GeoPackage -destination "platform=iOS Simulator,OS=latest,name=$latest_iphone"
+
+    - name: Test
+      run: |
+        iphone_names=$(xcrun simctl list devices available --json | jq -r '.devices | to_entries[] | .value[] | select(.name | test("^iPhone [0-9]+")) | .name')
+        if [ -z "$iphone_names" ]; then echo "Error: No iPhone simulators found."; exit 1; fi
+        latest_iphone=$(echo "$iphone_names" | sort | tail -n 1)
+        echo "latest_iphone: $latest_iphone"
+        xcodebuild test -scheme GeoPackage -destination "platform=iOS Simulator,OS=latest,name=$latest_iphone"
